### ISSUE TITLE
Can Not Import the EvolutionaryAlgorithmSearchCV Call

### ISSUE THREAD

**Issue by BernardOng** [rsteca/sklearn-deap#37]
Using the exact code sample, when I ran the code, I get an import error.

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    from evolutionary_search import EvolutionaryAlgorithmSearchCV
  File "D:\Anaconda2\lib\site-packages\evolutionary_search\__init__.py", line 1, in <module>
    from .cv import *
  File "D:\Anaconda2\lib\site-packages\evolutionary_search\cv.py", line 6, in <module>
    from deap import base, creator, tools, algorithms
  File "D:\Python\zillow\deap.py", line 25, in <module>
    from evolutionary_search import EvolutionaryAlgorithmSearchCV
ImportError: cannot import name EvolutionaryAlgorithmSearchCV

`import sklearn.datasets
import numpy as np
import random

data = sklearn.datasets.load_digits()
X = data["data"]
y = data["target"]

from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold

paramgrid = {"kernel": ["rbf"],
             "C"     : np.logspace(-9, 9, num=25, base=10),
             "gamma" : np.logspace(-9, 9, num=25, base=10)}

random.seed(1)

from evolutionary_search import EvolutionaryAlgorithmSearchCV
cv = EvolutionaryAlgorithmSearchCV(estimator=SVC(),
                                   params=paramgrid,
                                   scoring="accuracy",
                                   cv=StratifiedKFold(n_splits=4),
                                   verbose=1,
                                   population_size=50,
                                   gene_mutation_prob=0.10,
                                   gene_crossover_prob=0.5,
                                   tournament_size=3,
                                   generations_number=5,
                                   n_jobs=4)
cv.fit(X, y)`

**Comment by rsteca** [comment]
Hi! Many people have reported having problems with this library in an Anaconda environment. How did you install sklearn-deap?

**Comment by BernardOng** [comment]
I installed per instruction as follows (I used Windows 10 and Anaconda, 2x on main, 3x on env):
pip install sklearn-deap

Is there a way around this? Would installing from source make a difference?

**Comment by rsteca** [comment]
Maybe you can use a virtualenv environment instead of using anaconda?
