### ISSUE TITLE
Tests no longer pass with newest sklearn

### ISSUE THREAD

**Issue by jonringer** [rsteca/sklearn-deap#65]
Running the tests with the scikit-learn v0.21.1 yields this result

```
======================================================================
ERROR: test_cv (__main__.TestEvolutionarySearch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 48, in test_cv
    try_with_params()
  File "test.py", line 40, in try_with_params
    cv = readme()
  File "test.py", line 32, in readme
    generations_number=5)
  File "/build/source/evolutionary_search/cv.py", line 297, in __init__
    error_score=error_score)
TypeError: __init__() got an unexpected keyword argument 'fit_params'
```

Indeed, they did remove this argument, as shown here:
https://github.com/scikit-learn/scikit-learn/pull/13519

**Comment by rsteca** [comment]
Ok, thanks for the report, I'm going to check it out

**Comment by rsteca** [comment]
fixed
